version: "3.9"
services:
  web:
    container_name: webapp
    image: pongtanat/todoapp:latest
    ports:
      - 1235:1235
      - 80:80
    environment:
      - DB_HOST=${DB_HOST}
      - MSSQL_PASSWORD=${MSSQL_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      
    depends_on:
      - db
    networks:
      - mynetwork
    restart: always
  
  db:
    container_name: mssqldb
    image: mcr.microsoft.com/mssql/server:2019-CU16-GDR1-ubuntu-20.04
    volumes:
      - DB_VOL:/var/opt/mssql
    
    environment:
      - SA_PASSWORD=${MSSQL_PASSWORD}
      - MSSQL_PID=Express
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - mynetwork   

networks:
  mynetwork:
    driver: bridge

volumes:
  DB_VOL:
    external: true