version: "3.9"
services:
  db:
    container_name: mssqldb_dev
    image: mcr.microsoft.com/mssql/server:2019-CU16-GDR1-ubuntu-20.04
    volumes:
      - DB_VOL:/var/opt/mssql
    
    environment:
      - SA_PASSWORD=P@ssw0rd
      - MSSQL_PID=Express
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
volumes:
  DB_VOL:
    external: true
